USE BookStoreDB

CREATE TABLE Orders (
	OrderID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	OrderDate DATETIME2 NOT NULL,
	TotalAmount DECIMAL(19, 4) NOT NULL,
	OrderStatus NVARCHAR(15) NOT NULL,
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers(CustomerID)
)