USE [BookStoreDB]
GO

ALTER TABLE [dbo].[OrderItems] DROP CONSTRAINT [FK__OrderItem__BookI__5070F446]
GO

ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD FOREIGN KEY([BookID])
REFERENCES [dbo].[Books] ([BookID]) ON DELETE CASCADE
GO


