USE BookStoreDB

CREATE TABLE OrderItems (
	OrderItemID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Quanity INT NOT NULL,
	UnitPriceAtTimeOfTheOrder DECIMAL(19, 4) NOT NULL,
	BookID INT NOT NULL FOREIGN KEY REFERENCES Books(BookID),
	OrderID INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderID)
)