USE BookStoreDB

CREATE TABLE Customers (
	CustomerID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(62) NOT NULL UNIQUE,
	PhoneNumber VARCHAR(20) NOT NULL,
	ShippingAddress NVARCHAR(100) NOT NULL
)