USE BookStoreDB

CREATE TABLE Books (
	BookID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	Title NVARCHAR(500) NOT NULL,
	ISBN VARCHAR(17) NOT NULL UNIQUE,
	PublicationYear DATETIME2 NOT NULL,
	Price DECIMAL(19, 4) NOT NULL,
	StockQuantity INT NOT NULL
)